import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Services from '@/components/Services'
import About from '@/components/About'
import Banner from '@/components/Banner'
import Project from '@/components/Project'
import Whychooseus from '@/components/Whychooseus'
import Team from '@/components/Team'
import Testimonial from '@/components/Testimonial'
import Blog from '@/components/Blog'
// The following import prevents a Font Awesome icon server-side rendering bug,
// where the icons flash from a very large icon down to a properly sized one:
import '@fortawesome/fontawesome-svg-core/styles.css';
// Prevent fontawesome from adding its CSS since we did it manually above:
import { config } from '@fortawesome/fontawesome-svg-core'
config.autoAddCss = false; /* eslint-disable import/first */
import Contact from '@/components/Contact'
import Footer from '@/components/Footer'



export default function Home() {
  return (
    <>
      <Head>
        <title>Logistics App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <Services />
      <About />
      <Project />
      <Testimonial />
      <Whychooseus />
      <Blog />
      <Team />
      <Contact />
      <Footer />
    </>
  )
}
